### ISSUE TITLE
some test commands are incorrectly parsed

### ISSUE THREAD

**Issue by peckato1** [syyyr/gdb-ctest#4]
Hello syyyr :) Thanks for this tool we still use :)

In our `CMakeLists.txt` we have something like this (a test `COMMAND` spanning over multiple lines, first line is also terminated by semicolon).

```
add_test(NAME test-${TEST_NAME}
    COMMAND ${UNSHARE_EXECUTABLE} -r -m sh -c "set -ex $<SEMICOLON>
        ${MOUNT_EXECUTABLE} -t tmpfs none /tmp $<SEMICOLON>
        export LD_PRELOAD=${pam_wrapper_LDFLAGS} PAM_WRAPPER_SERVICE_DIR=${CMAKE_CURRENT_BINARY_DIR}/tests/pam PAM_WRAPPER=1 UID_WRAPPER_DISABLE_DEEPBIND=1 $<SEMICOLON>
        $<TARGET_FILE:test-${TEST_NAME}>")
```

When I run gdb-ctest, it prompts me that the following will be run:

```
Will run this as the test command for 'test-restconf-reading' (gdb is included):
  $ (...) gdb --args /usr/bin/unshare -r -m sh -c set -ex ;
```

i.e., it seems that only the first line is reported (and probably also run) because in `gdb` I see

```
(gdb) r
Starting program: /usr/bin/unshare -r -m sh -c set -ex \;
```

which seems wrong.

(well let me state that running gdb on `unshare` command is useless itself, we want to run `gdb` on the executable running in the `unshare`, but that is another issue)

**Comment by syyyr** [comment]
Hi Tom, I'll try to look into this.

**Comment by syyyr** [comment]
Please try the current main branch, the problem should be fixed.

**Comment by peckato1** [comment]
Thanks! Now it seems to be correct :)
