### ISSUE TITLE
PKGBUILD in AUR

### ISSUE THREAD

**Issue by peckato1** [syyyr/gdb-ctest#5]
Hi, I think [this update of `PKGBUILD` in AUR](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=gdb-ctest-git&id=24d20aaeca42b14bb1b4068834624cd82608ecc1) is wrong. You are setting 644 permissions (`rw-/r--/r--`) for the `gdb-ctest`, so there are no execute permissions for anybody. I think it should be `rwx/r-x/r-x`, i.e., 755.

**Comment by syyyr** [comment]
Oops, I forgot to push the fix.
https://aur.archlinux.org/cgit/aur.git/commit/?h=gdb-ctest-git&id=c4796115204aa11335fc605dda2389fda3bee42d

**Comment by peckato1** [comment]
thanks! :)
